name: ddev-letstalk-challenge
networks:
    ddev_default:
        external: true
        name: ddev_default
    default:
        labels:
            com.ddev.platform: ddev
        name: ddev-letstalk-challenge_default
services:
    db:
        build:
            args:
                BASE_IMAGE: ddev/ddev-dbserver-mariadb-10.11:v1.23.3
                gid: "1000"
                uid: "1000"
                username: rico
            context: /mnt/c/Users/ricoi/PhpstormProjects/letstalk-challenge/.ddev/.dbimageBuild
            dockerfile: Dockerfile
        cap_add:
            - SYS_NICE
        command: []
        container_name: ddev-letstalk-challenge-db
        environment:
            COLUMNS: "265"
            DDEV_DATABASE: mariadb:10.11
            DDEV_DATABASE_FAMILY: mysql
            DDEV_HOSTNAME: letstalk-challenge.ddev.site
            DDEV_PHP_VERSION: "8.2"
            DDEV_PRIMARY_URL: https://letstalk-challenge.ddev.site
            DDEV_PROJECT: letstalk-challenge
            DDEV_PROJECT_TYPE: laravel
            DDEV_ROUTER_HTTP_PORT: "80"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SITENAME: letstalk-challenge
            DDEV_TLD: ddev.site
            DOCKER_IP: 127.0.0.1
            GOARCH: amd64
            GOOS: linux
            HOST_DOCKER_INTERNAL_IP: ""
            IS_DDEV_PROJECT: "true"
            LINES: "14"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/letstalk-challenge-db/mysql_history
            MYSQL_PWD: db
            PGDATABASE: db
            PGHOST: 127.0.0.1
            PGPASSWORD: db
            PGUSER: db
            POSTGRES_DB: db
            POSTGRES_PASSWORD: db
            POSTGRES_USER: db
            TZ: ""
            USER: rico
        healthcheck:
            interval: 1s
            retries: 120
            start_interval: 1s
            start_period: 2m0s
            timeout: 1m10s
        hostname: letstalk-challenge-db
        image: ddev/ddev-dbserver-mariadb-10.11:v1.23.3-letstalk-challenge-built
        labels:
            com.ddev.app-type: laravel
            com.ddev.approot: /mnt/c/Users/ricoi/PhpstormProjects/letstalk-challenge
            com.ddev.platform: ddev
            com.ddev.site-name: letstalk-challenge
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 3306
        restart: "no"
        stop_grace_period: 1m0s
        user: 1000:1000
        volumes:
            - source: database
              target: /var/lib/mysql
              type: volume
              volume:
                nocopy: true
            - bind:
                create_host_path: true
              source: /mnt/c/Users/ricoi/PhpstormProjects/letstalk-challenge/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              source: /mnt/c/Users/ricoi/PhpstormProjects/letstalk-challenge/.ddev/db_snapshots
              target: /mnt/snapshots
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
        working_dir: /home/rico
    web:
        build:
            args:
                BASE_IMAGE: ddev/ddev-webserver:v1.23.3
                DDEV_DATABASE: mariadb:10.11
                DDEV_PHP_VERSION: "8.2"
                gid: "1000"
                uid: "1000"
                username: rico
            context: /mnt/c/Users/ricoi/PhpstormProjects/letstalk-challenge/.ddev/.webimageBuild
            dockerfile: Dockerfile
        cap_add:
            - SYS_PTRACE
        command:
            - /pre-start.sh
        container_name: ddev-letstalk-challenge-web
        environment:
            COLUMNS: "265"
            COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"
            COREPACK_HOME: /mnt/ddev-global-cache/corepack
            DDEV_COMPOSER_ROOT: /var/www/html
            DDEV_DATABASE: mariadb:10.11
            DDEV_DATABASE_FAMILY: mysql
            DDEV_DOCROOT: public
            DDEV_FILES_DIR: ""
            DDEV_FILES_DIRS: ""
            DDEV_HOSTNAME: letstalk-challenge.ddev.site
            DDEV_MUTAGEN_ENABLED: "false"
            DDEV_PHP_VERSION: "8.2"
            DDEV_PRIMARY_URL: https://letstalk-challenge.ddev.site
            DDEV_PROJECT: letstalk-challenge
            DDEV_PROJECT_TYPE: laravel
            DDEV_ROUTER_HTTP_PORT: "80"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SITENAME: letstalk-challenge
            DDEV_TLD: ddev.site
            DDEV_VERSION: v1.23.3
            DDEV_WEB_ENTRYPOINT: /mnt/ddev_config/web-entrypoint.d
            DDEV_WEBSERVER_TYPE: nginx-fpm
            DDEV_XDEBUG_ENABLED: "false"
            DEPLOY_NAME: local
            DOCKER_IP: 127.0.0.1
            DOCROOT: public
            DRUSH_ALLOW_XDEBUG: "1"
            DRUSH_OPTIONS_URI: https://letstalk-challenge.ddev.site
            GOARCH: amd64
            GOOS: linux
            HOST_DOCKER_INTERNAL_IP: ""
            HTTP_EXPOSE: 80:80,8025:8025,5172:5173
            HTTPS_EXPOSE: 443:80,8026:8025,5173:5173
            IS_DDEV_PROJECT: "true"
            LINES: "14"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/letstalk-challenge-web/mysql_history
            MYSQL_PWD: db
            NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
            PGDATABASE: db
            PGHOST: db
            PGPASSWORD: db
            PGUSER: db
            PHP_IDE_CONFIG: serverName=letstalk-challenge.ddev.site
            SSH_AUTH_SOCK: /home/.ssh-agent/socket
            TZ: ""
            USER: rico
            VIRTUAL_HOST: letstalk-challenge.ddev.site
            npm_config_cache: /mnt/ddev-global-cache/npm
        expose:
            - "5173"
        external_links:
            - ddev-router:letstalk-challenge.ddev.site
        healthcheck:
            interval: 1s
            retries: 120
            start_interval: 1s
            start_period: 2m0s
            timeout: 1m10s
        hostname: letstalk-challenge-web
        image: ddev/ddev-webserver:v1.23.3-letstalk-challenge-built
        labels:
            com.ddev.app-type: laravel
            com.ddev.approot: /mnt/c/Users/ricoi/PhpstormProjects/letstalk-challenge
            com.ddev.platform: ddev
            com.ddev.site-name: letstalk-challenge
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 80
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 443
        restart: "no"
        user: 1000:1000
        volumes:
            - consistency: cached
              source: ../
              target: /var/www/html
              type: bind
            - bind:
                create_host_path: true
              read_only: true
              source: /mnt/c/Users/ricoi/PhpstormProjects/letstalk-challenge/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              read_only: true
              source: /mnt/c/Users/ricoi/PhpstormProjects/letstalk-challenge/.ddev/xhprof
              target: /usr/local/bin/xhprof
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
            - source: ddev-ssh-agent_socket_dir
              target: /home/.ssh-agent
              type: volume
              volume: {}
        working_dir: /var/www/html/
volumes:
    database:
        external: true
        name: letstalk-challenge-mariadb
    ddev-global-cache:
        external: true
        name: ddev-global-cache
    ddev-ssh-agent_socket_dir:
        external: true
        name: ddev-ssh-agent_socket_dir
